### ISSUE TITLE
access to th_ycbcr_buffer info

### ISSUE THREAD

**Issue by vividsnow** [vigith/Ogg-Theora-LibTheora#1]
hi

Thank you for providing libtheora bindings for perl!
Could you add function (get_th_ycbcr_buffer_info?) which will return pointer,width,height,stride to data of "th_img_plane"'s of "th_ycbcr_buffer", so pointers can be passed as arguments to "OpenGL::Array->new_pointer"?

best regards

**Comment by vigith** [comment]
Hello Vividsnow,

If you see the code, you will see 3 sets of width, height and stride

```
ycbcr[0].width  = w;
ycbcr[0].height = h;
ycbcr[0].stride = w;

ycbcr[1].width  = w/2;
ycbcr[1].height = h/2;
ycbcr[1].stride = w/2;

ycbcr[2].width  = w/2;
ycbcr[2].height = h/2;
ycbcr[2].stride = w/2;
```

How do you want me to provide these?

Could you be more specific about the input and the output arguments (data type) etc?

**Comment by vividsnow** [comment]
Hi 

Thank you for response - maybe just arrayref of hashrefs?

``` perl
my $th_ycbcr_buffer = make_th_ycbcr_buffer();
... # decode packe
my $info = get_th_ycbcr_buffer($th_ycbcr_buffer); # returns
[
    { width => w, height => h, stride => w, data => data_pointer }, # Y plane
    { ... }, #  Cb plane
    { ... } # Cr plane
]
```

p.s.
It seems that width and height of chroma planes depends on pixel format (th_info::pixel_fmt), this can affect rgb<->ycbcr converting functions (rgb_th_encode_ycbcr_in, ycbcr_to_rgb_buffer)
( http://www.theora.org/doc/libtheora-1.0/codec_8h.html#5c9e7f2f0c7ed209c9ca3ed0abd328bc )

best regards

**Comment by vigith** [comment]
Hello Vividsnow,

I have added the function 'get_th_ycbcr_buffer_info'. It returns an arrayref of hashrefs containing width, height, stride
and data_pointer for each plane. I haven't pushed this changes to CPAN yet, will push once this issue can be closed.

About the conversions (rgb <=> ycbcr), i just wrote basic ones to test my code. You can optimize based the the architecture you are using (GPU processors even have mnemonics for it).

Patches are welcome :-)

**Comment by vividsnow** [comment]
Thank you! I will test/fix it, add OpenGL::Array example and make pull request

**Comment by vividsnow** [comment]
Hi again! ) 
I'm always getting first frame data from loop calling "th_decode_packetin"->"th_decode_ycbcr_out"->"ycbcr_to_rgb_buffer / get_th_ycbcr_buffer_info"
Did you test the module on getting subsequent frames? Can you share an example?

**Comment by vigith** [comment]
Hello,

Could you please share your code? I will take a look into it. How are you sure that you are getting the same frame? (Please make sure your code is commented :-)

**Comment by vividsnow** [comment]
Hi

https://gist.github.com/5849b17fb4dee88cd2eb - slightly modified code from  [decode example](http://search.cpan.org/~vigith/Ogg-Theora-LibTheora-0.03/lib/Ogg/Theora/LibTheora.pm#SYNOPSIS_DECODE)
It receives filename as script argument and writes raw file for each frame into current dir.

Than you can perform: "diff -s file1 file2" on any two output files - I got identical )

**Comment by vividsnow** [comment]
Get it - I forgot to read packets using ogg_read_page )

**Comment by vigith** [comment]
true :-) . Anyways i have pushed an example code @ https://github.com/vigith/Ogg-Theora-LibTheora/tree/master/examples

**Comment by vigith** [comment]
I am reverting the type changes (ie, int to IV, unsigned int to UV etc) made to LibTheora.xs, to remove the warnings from make (warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]).

**Comment by vividsnow** [comment]
Strange, I made these changes to avoid same warnings (debian, x86_64)

**Comment by vigith** [comment]
pushed version 0.04 to CPAN.
